config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :account_sessions, only: [:new, :create, :destroy]

  resources :tasks do
    put :sort
  end
  resources :accounts

end

app/models/account.rb
class Account < ApplicationRecord
  authenticates_with_sorcery!
  has_secure_password

  validates :login,                 presence: true, uniqueness: true
  validates :password,              presence: true
  validates :password_confirmation, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title,   presence: true
  validates :content, presence: true

  include RankedModel
  ranks :row_order
end

app/controllers/account_sessions_controller.rb
class AccountSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destory]

  def new
    @account = Account.new
  end

  def create
    if @account = login(params[:login], params[:password])
      redirect_back_or_to(tasks_path, notice: 'ログインしました')
    else
      flash.now[:alert] = 'ログイン失敗'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(new_account_session_path, notice: 'ログアウトしました')
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:index, :new, :create]

  # GET /accounts
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /accounts/1
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /accounts/1
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:login, :password, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :require_login

  private
    def not_authenticated
      redirect_to new_account_session_path, alert: "まずログインしてください"
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  def index
    @toptask = Task.last
    @tasks = Task.rank(:row_order)

  end

  # GET /tasks/1
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'タスクを作成しました' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /tasks/1
  def update
    respond_to do |format|
      if @task.update(task_params)
        if params[:task][:finished] == "true"
          format.html { redirect_to tasks_path, notice: 'タスクを完了しました' }
        else
          format.html { redirect_to tasks_path, notice: 'タスクを編集しました' }
        end
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'タスクを削除しました.' }
    end
  end

  def sort
    task = Task.find(params[:task_id])
    task.update(task_params)
    render nothing: true
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.fetch(:task, {}).permit(:title, :content, :priority, :finished,:row_order_position).merge(account_id:current_user.id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/account_sessions/_form.html.haml
%h1 Sessions#new
= form_tag account_sessions_path, id: "session-form", method: :post do
  .div
    = label_tag :login
    = text_field_tag :login
  .div
    = label_tag :password
    = password_field_tag :password
  .div
    = submit_tag "Login"

app/views/account_sessions/create.html.haml
%h1 AccountSessions#create
%p Find me in app/views/account_sessions/create.html.haml

app/views/account_sessions/destroy.html.haml
%h1 AccountSessions#destroy
%p Find me in app/views/account_sessions/destroy.html.haml

app/views/account_sessions/new.html.haml
%h1 ログイン

= render 'form'

= link_to '戻る', new_account_session_path

app/views/accounts/_form.html.haml
= form_for @account do |f|
  - if @account.errors.any?
    #error_explanation
      %h2= "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
      %ul
        - @account.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :login
    = f.text_field :login
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions
    = f.submit 'Save'

app/views/accounts/edit.html.haml
%h1 Editing account

= render 'form'

= link_to 'Show', @account
\|
= link_to 'Back', accounts_path

app/views/accounts/index.html.haml
%h1 Listing accounts

%table
  %thead
    %tr
      %th Login
      %th
      %th
      %th

  %tbody
    - @accounts.each do |account|
      %tr
        %td= account.login
        %td= link_to 'Show', account
        %td= link_to 'Edit', edit_account_path(account)
        %td= link_to 'Destroy', account, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Account', new_account_path

app/views/accounts/new.html.haml
%h1 New account

= render 'form'

= link_to 'Back', accounts_path

app/views/accounts/show.html.haml
%p#notice= notice

%p
  %b Login:
  = @account.login
%p
  %b Password digest:
  = @account.password_digest

= link_to 'Edit', edit_account_path(@account)
\|
= link_to 'Back', accounts_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title KOtani
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    -flash.each do |key,value|
      =content_tag :div, value, class: "flash-#{key}"
    = yield

app/views/tasks/_edit-form.html.haml
= form_for @task do |f|
  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, "件のエラーがあります。")}"
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg

  .edit-title-empty
  .actions
    タイトル
  .actions
    = f.text_field :title, placeholder:'タイトル', class: "edit-title-form"

  .edit-content-empty
  .actions
    本文
  .actions
    = f.text_field :content, placeholder:'本文', class: "edit-content-form"

  .actions
    = f.submit '編集する', class: 'edit-task_submit'

app/views/tasks/_form.html.haml
= form_for @task do |f|
  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, "件のエラーがあります。")}"
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg

  #title-empty
  .actions
    タイトル
  .actions
    = f.text_field :title, placeholder:'タイトル'

  #content-empty
  .actions
    本文
  .actions
    = f.text_field :content, placeholder:'本文'
  .actions
    = f.select :priority, [['優先度1', 1], ['優先度2', 2], ['優先度3', 3]]
  .actions
    = f.submit '作成', id: 'task_submit'

app/views/tasks/_task.html.haml
- if task.finished == false
  %tr.task-list.item{ data: { model_name: task.class.name.underscore, update_url: task_sort_path(task) }}
    %td.task-title
      = task.title.truncate(13)
    %td.task-content
      = task.content.truncate(13)
    %td.task-footer
      = link_to '編集', edit_task_path(task.id)
      %td.task-complete
        = form_for(task) do |f|
          = f.hidden_field :finished, value: "true"
          = f.submit "完了"

app/views/tasks/edit.html.haml
%h1 タスク編集画面

= render 'edit-form'


= link_to '戻る', tasks_path

app/views/tasks/index.html.haml
%h1 タスク一覧
.task-list-new
  .task-title
    = @toptask.title.truncate(13)
  .task-content
    = @toptask.content.truncate(13)
  .task-footer
    = link_to '編集', edit_task_path(@toptask.id)
    .task-complete
      = form_for(@toptask) do |f|
        = f.hidden_field :finished, value: "true"
        = f.submit "完了"
.task-new
  ←New!
%table.table.table-bordered.table-sortable
  %tbody
    = render partial: 'task', collection: @tasks

%br

= link_to 'タスク新規作成', new_task_path

= link_to 'ログアウト', account_session_path(current_user.id), method: :delete if current_user

app/views/tasks/new.html.haml
%h1 タスク新規作成画面
= render 'form'

= link_to '戻る', tasks_path

app/views/tasks/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path